language: python

python:
    - "2.6"
    - "2.7"

env:
    - DJANGO=1.4.11

virtualenv:
    system_site_packages: true

before_install:
    - env | sort
    - sudo apt-get update -qq
    - sudo apt-get install -qq python-yaml
    - git remote add upstream git://github.com/cbmi/varify.git
    - upstream=master;
      if [ "$TRAVIS_PULL_REQUEST" != false ]; then
          upstream=$TRAVIS_BRANCH;
      fi;
      git fetch --append --no-tags upstream refs/heads/$upstream:refs/remotes/upstream/$upstream
    - /usr/bin/python bin/check_signoff.py

install:
    - pip install -q coveralls Django==$DJANGO --use-mirrors
    - pip install -r requirements.txt
    - "if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install --use-mirrors cython && pip install --use-mirrors pysam argparse counter ordereddict importlib; fi"
    - pip install flake8
    - pip install httpretty

services:
    - memcached
    - redis-server

before_script:
    - flake8
    - psql -c 'create database varifydb;' -U postgres

script:
    - coverage run test_suite.py

after_success:
    - coveralls
